/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/ftball.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.49, 0.25, 0.29]}>
        <mesh geometry={nodes.Icosphere_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Icosphere_2.geometry} material={materials.Black} />
      </group>
    </group>
  )
}

useGLTF.preload('/ftball.glb')
